### ISSUE TITLE
Crashes on Windows 11

### ISSUE THREAD

**Issue by init5-SF** [GhostPack/SharpDPAPI#33]
hi, just grabbed the latest version and compiled it (release, not debug)
I get the below error on Windows 11 (23H2)

![image](https://github.com/GhostPack/SharpDPAPI/assets/10214861/af22386e-db54-4b72-9b96-94feaba64d03)

Text error:

```
C:\tools\SharpDPAPI\SharpDPAPI\bin\Release>whoami
nt authority\system

C:\tools\SharpDPAPI\SharpDPAPI\bin\Release>SharpDPAPI.exe machinetriage

  __                 _   _       _ ___
 (_  |_   _. ._ ._  | \ |_) /\  |_) |
 __) | | (_| |  |_) |_/ |  /--\ |  _|_
                |
  v1.11.3


[*] Action: Machine DPAPI Credential, Vault, and Certificate Triage


[!] Unhandled SharpDPAPI exception:

System.Security.Cryptography.CryptographicException: The cipher mode specified requires that an initialization vector (IV) be used.
   at System.Security.Cryptography.CapiSymmetricAlgorithm.ProcessIV(Byte[] iv, Int32 blockSize, CipherMode cipherMode)
   at System.Security.Cryptography.CapiSymmetricAlgorithm..ctor(Int32 blockSize, Int32 feedbackSize, SafeCspHandle provider, SafeCapiKeyHandle key, Byte[] iv, CipherMode cipherMode, PaddingMode paddingMode, EncryptionMode encryptionMode)
   at System.Security.Cryptography.AesCryptoServiceProvider.CreateDecryptor(SafeCapiKeyHandle key, Byte[] iv)
   at SharpDPAPI.Crypto.LSAAESDecrypt(Byte[] key, Byte[] data)
   at SharpDPAPI.LSADump.GetLSAKey()
   at SharpDPAPI.LSADump.GetLSASecret(String secretName)
   at SharpDPAPI.LSADump.GetDPAPIKeys(Boolean show)
   at SharpDPAPI.Triage.TriageSystemMasterKeys(Boolean show)
   at SharpDPAPI.Commands.Machinetriage.Execute(Dictionary`2 arguments)
   at SharpDPAPI.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at SharpDPAPI.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)


SharpDPAPI completed in 00:00:00.0240340
```

**Comment by jsdhasfedssad** [comment]
I get the same error executing the same command but on Windows 10.

**Comment by subat0mik** [comment]
This is not related to Win10 vs Win11 (as far as I can tell).

PR #29 swapped the managed crypto APIs for the crypto provider APIs. The author states this was not fully tested. Specifically, the exception above is thrown when running `sccm` and `machinetriage` commands. Within the `LSAAESDecrypt` function, an `AesCryptoServiceProvider` object is created. As a simple fix, you can change it to create an `AesManaged` object instead:

Change line 269 from this: `var aesCryptoProvider = new AesCryptoServiceProvider();`
To this: `var aesCryptoProvider = new AesManaged();`

I'm conducting further testing to try to get it working with `AesCryptoServiceProvider`.

**Comment by leechristensen** [comment]
This should be fixed now with the above merge!
