### ISSUE TITLE
Fails to run SharpChrome when Chrome is open

### ISSUE THREAD

**Issue by fk4125** [GhostPack/SharpDPAPI#38]
![4trGk5jDoV](https://github.com/GhostPack/SharpDPAPI/assets/94907861/cd108a28-c426-4f8b-a966-7476bd42cedc)

Got error when Chrome  is open.
Using  SharpChrome v1.12.0, Windows 11, Google Chrome Version 122.0.6261.129
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpChrome.Chrome.ParseChromeCookies(Dictionary`2 MasterKeys, String cookieFilePath, String displayFormat, Boolean showAll, Boolean unprotect, String cookieRegex, String urlRegex, Boolean setneverexpire, Byte[] aesStateKey, Boolean quiet)
   at SharpChrome.Chrome.TriageChromeCookies(Dictionary`2 MasterKeys, String computerName, String userFolder, String displayFormat, Boolean showAll, Boolean unprotect, String cookieRegex, String urlRegex, Boolean setneverexpire, String stateKey, String browser, Boolean quiet)
   at SharpChrome.Commands.Cookies.Execute(Dictionary`2 arguments)
   at SharpChrome.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at SharpChrome.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)
```

**Comment by RickConsole** [comment]
This is because the Cookies file in the chrome directory is a SQLite DB, and chrome keeps it open, preventing you from accessing it. A more informative error message here would be the only fix I imagine.
