### ISSUE TITLE
[!] Unhandled SharpDPAPI exception:

### ISSUE THREAD

**Issue by Papotito123** [GhostPack/SharpDPAPI#5]
Hello:
When running sharpdpapi.exe I getting this:

C:\Users\TESTACCOUNT\Downloads\SharpDPAPI-master\SharpDPAPI-master\SharpDPAPI-master\SharpDPAPI\bin\Release>SharpDPAPI.exe machinevaults

  __                 _   _       _ ___
 (_  |_   _. ._ ._  | \ |_) /\  |_) |
 __) | | (_| |  |_) |_/ |  /--\ |  _|_
                |
  v1.6.1

[*] Action: Machine DPAPI Vault Triage

[*] Elevating to SYSTEM via token duplication for LSA secret retrieval
[*] RevertToSelf()

[*] Secret  : DPAPI_SYSTEM
[*]    full: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[*]    m/u : xxxxxxxxxxxxxxxxxxxxxxx / xxxxxxxxxxxxxxxxxxxxxxxxxx

[!] Unhandled SharpDPAPI exception:

System.UnauthorizedAccessException: Access to the path 'C:\Windows\System32\Microsoft\Protect\Recovery\Recovery.dat{8bf0a20f-5420-11e9-ac9f-e84e06061855}.TM.blf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SharpDPAPI.Triage.TriageSystemMasterKeys(Boolean show)
   at SharpDPAPI.Commands.Machinevaults.Execute(Dictionary`2 arguments)
   at SharpDPAPI.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at SharpDPAPI.Program.Main(String[] args)

My sharpchrome.exe compiled run well.

Any info much appreciated.

**Comment by Papotito123** [comment]
Hello:
No problem.
